// REDUX ACTION TYPES
export enum ActionTypes {
  LOAD_USER = 'LOAD_USER',
  LOGOUT_USER = 'LOGOUT_USER',
  LOAD_USER_PROFILE = 'LOAD_USER_PROFILE',
  LOAD_TAGS = 'LOAD_TAGS',
  LOAD_CATS = 'LOAD_CATS',
  CLEAR_TAGS_CATS = 'CLEAR_TAGS_CATS'
}

export const LOAD_USER = 'LOAD_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOAD_USER_PROFILE = 'LOAD_USER_PROFILE';
export const LOAD_TAGS = 'LOAD_TAGS';
export const LOAD_CATS = 'LOAD_CATS';
export const CLEAR_TAGS_CATS = 'CLEAR_TAGS_CATS';
